# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:57
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='Categorias')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebok:')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter:')),
                ('website_url', models.URLField(blank=True, verbose_name='Página Pessoal:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
