# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.URLField(blank=True, verbose_name='Email')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebok:')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter:')),
                ('website_url', models.URLField(blank=True, verbose_name='Página Pessoal:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
