# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='comment outline', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
    ]
