# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161130_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização'),
        ),
    ]
